### ISSUE TITLE
ImportError at /portfolio No module named http.client

### ISSUE THREAD

**Issue by patel-dhaval** [Amay22/PyFolio#8]
Hey! 
Python 2.7 doesn't have http.client and has httplib.
I replaced it and after making a few changes, I'm getting an error of TypeError at /portfolio
'NoneType' object has no attribute '__getitem__' , when I try searching for any stock !
Any help would be appreciated !

**Comment by Amay22** [comment]
Use Python 3.something it's not built on 2.7
